// Slang and shortcuts
"use strict";
var GHOST = GHOST || {};

GHOST.slang = {
    "intresting": "interesting",
    "ballons": "balloons",
    "baloons": "balloons",
    "balons": "balloons",
    "ballon": "balloon",
    "baloon": "balloon",
    "balon": "balloon",
    "eyecolor": "eye color",
    "eyecolour": "eye color",
    "boyfrined": "boyfriend",
    "untill": "until",
    "grey": "gray",
    "ocre": "ochre",
    "sayonara": "sayounara",
    "ahppy": "happy",
    "allredy": "already",
    "anoying": "annoying",
    "appriciated": "appreciated",
    "bcz": "because",
    "becus": "because",
    "wonderfull": "wonderful",
    "bunnys": "bunnies",
    "c'mon": "come on",
    "canadien": "canadian",
    "cawboy": "cowboy",
    "ceerpy": "creepy",
    "cellphone": "cell phone",
    "cloor": "color",
    "deth": "death",
    "dunb": "dumb",
    "dvh's": "dvh",
    "e-mail": "email",
    "gift-giving": "giving gifts",
    "everthing": "everything",
    "faveret": "favorite",
    "favrit": "favorite",
    "forgven": "forgiven",
    "ghosyt": "ghost",
    "gilfreiend": "girlfriend",
    "girfreind": "girlfriend",
    "girlriend": "girlfriend",
    "goout": "go out",
    "grilfriend": "girlfriend",
    "heeloo": "hello",
    "hom": "home",
    "homwork": "homework",
    "housse": "house",
    "huspend": "husband",
    "idior": "idiot",
    "impossable": "impossible",
    "inpersive": "impressive",
    "intersting": "interesting",
    "jhon": "john",
    "kil": "kill",
    "knoww": "know",
    "konnichiha": "konnichiwa",
    "lik": "like",
    "liying": "lying",
    "maried": "married",
    "masheen": "machine",
    "mesn": "mean",
    "mt": "my",
    "mums": "mom's",
    "myslf": "myself",
    "naem": "name",
    "nicname": "nickname",
    "nither": "neither",
    "peple": "people",
    "perso": "person",
    "pinapples": "pineapples",
    "pleae": "please",
    "pregnent": "pregnant",
    "regected": "rejected",
    "righ": "right",
    "shool": "school",
    "skerrd": "scared",
    "skhool": "school",
    "smoething": "something",
    "sorta": "sort of",
    "stolker": "stalker",
    "superpowers": "super power",
    "swea": "swear",
    "tday": "today",
    "thats's": "that is",
    "tikle": "tickle",
    "tolett": "toilet",
    "whaat": "what",
    "whas": "what is",
    "wheather": "weather",
    "whee": "where",
    "whol": "whole",
    "youreself": "yourself",
    "youtbe": "youtube",
    "2nite": "tonight",
    "anoy": "annoy",
    "ans": "and",
    "baack": "back",
    "basterd": "bastard",
    "broclie": "broccoli",
    "byye": "bye",
    "chismas": "christmas",
    "chrisemas": "christmas",
    "conputer": "computer",
    "crismis": "christmas",
    "cuhrch": "church",
    "din't": "didn't",
    "dinsney": "disney",
    "dohnuts": "doughnuts",
    "execpt": "except",
    "favoriet": "favorite",
    "favorit": "favorite",
    "favoritte": "favorite",
    "favrote": "favorite",
    "frensh": "french",
    "frineds": "friends",
    "friut": "fruit",
    "gaay": "gay",
    "girlfiend": "girlfriend",
    "girlfirend": "girlfriend",
    "gjhost": "ghost",
    "gosty": "ghost",
    "gota": "got a",
    "guhost": "ghost",
    "hallowmeen": "halloween",
    "hallween": "halloween",
    "hardd": "hard",
    "havr": "have",
    "heven": "heaven",
    "humaine": "human",
    "hunan": "human",
    "ihate": "i hate",
    "ilke": "like",
    "iḿ": "i'm",
    "imma": "i am a",
    "innopropriste": "inappropriate",
    "ism't": "isn't",
    "itś": "it is",
    "it's": "it is",
    "they're": "they are",
    "kide": "kid",
    "knok": "knock",
    "lazagna": "lasagna",
    "liive": "live",
    "littel": "little",
    "locatin": "location",
    "macking": "making",
    "mcdoans": "mcdonald's",
    "mincraft": "minecraft",
    "minuts": "minutes",
    "mornin": "morning",
    "mw": "me",
    "nartuo": "naruto",
    "oic": "picture",
    "ookkaayy": "ok",
    "peaple": "people",
    "perfrct": "perfect",
    "pezza": "pizza",
    "presedent": "president",
    "princes": "princess",
    "problrm": "problem",
    "reallyy": "really",
    "rilly": "really",
    "rood": "rude",
    "samwitches": "sandwich",
    "selff": "self",
    "shud": "should",
    "shur": "sure",
    "smthing": "something",
    "sonh": "song",
    "sopchect": "subject",
    "thoghtg": "thought",
    "tmorow": "tomorrow",
    "tnight": "tonight",
    "tomorw": "tomorrow",
    "trangender": "transgender",
    "traying": "trying",
    "trnsgender": "transgender",
    "typeing": "typing",
    "ugley": "ugly",
    "usermane": "username",
    "waassup": "what is up",
    "wasup": "what is up",
    "wath": "what",
    "wjere": "where",
    "xan": "can",
    "yaeh": "yeah",
    "abouy": "about",
    "afer": "after",
    "agian": "again",
    "aparment": "apartment",
    "arre": "are",
    "atitude": "attitude",
    "atractive": "attractive",
    "becouse": "because",
    "bilt": "built",
    "bourd": "bored",
    "butifull": "beautiful",
    "childrin": "children",
    "chirsmas": "christmas",
    "chritsmas": "christmas",
    "condome": "condom",
    "cryy": "cry",
    "cuputer": "computer",
    "divice": "device",
    "doea": "does",
    "doggystyle": "doggy style",
    "europ": "europe",
    "favriote": "favorite",
    "favruit": "favorite",
    "ghoat": "ghost",
    "ghostr": "ghost",
    "ghsst": "ghost",
    "giberish": "gibberish",
    "girlfreide": "girlfriend",
    "goust": "ghost",
    "grl": "girl",
    "gusse": "guess",
    "hav": "have",
    "hieght": "height",
    "hummen": "human",
    "hve": "have",
    "idiote": "idiot",
    "iim": "i'm",
    "ilumiati": "illuminati",
    "inapropriate": "inappropriate",
    "innapropriat": "inappropriate",
    "jiberrish": "gibberish",
    "knwo": "know",
    "losre": "loser",
    "manster": "monster",
    "masterbashen": "masturbation",
    "mastubation": "masturbation",
    "memmes": "memes",
    "nnuts": "nuts",
    "odn't": "don't",
    "ofc": "of course",
    "peice": "piece",
    "phisical": "physical",
    "posses": "possess",
    "preganet": "pregnant",
    "resuarnt": "restaurant",
    "salmonela": "salmonella",
    "sisster": "sister",
    "sistre": "sister",
    "sorrt": "sorry",
    "sory": "sorry",
    "stinck": "stink",
    "stp": "stop",
    "tak": "take",
    "thankgive": "thanksgiving",
    "thst": "that",
    "tommorrow": "tomorrow",
    "triggerd": "triggered",
    "undefind": "undefined",
    "wall-nuts": "walnuts",
    "whhy": "why",
    "whst": "what",
    "whyy": "why",
    "wight": "weight",
    "wiil": "will",
    "worng": "wrong",
    "yourslef": "yourself",
    "youve": "you have",
    "yyeess": "yes",
    "aam": "am",
    "anyhting": "anything",
    "arn't": "aren't",
    "awhats": "what is",
    "babie": "baby",
    "bck": "back",
    "becuz": "because",
    "bestfriend": "best friend",
    "boii": "boy",
    "couision": "cousin",
    "ddie": "die",
    "desighn": "design",
    "diying": "dying",
    "enemys": "enemies",
    "eys": "eyes",
    "favourt": "favorite",
    "favrite": "favorite",
    "fcuk": "fuck",
    "fuuny": "funny",
    "fvorite": "favorite",
    "gn": "good night",
    "good-evening": "good evening",
    "guirl": "girl",
    "ha-ha": "haha",
    "hahahahha": "haha",
    "hahha": "haha",
    "hallowen": "halloween",
    "haveto": "have to",
    "kunfu": "kung fu",
    "kungfu": "kung fu",
    "like's": "likes",
    "moring": "morning",
    "nah": "no",
    "oohh": "oh",
    "perenets": "parents",
    "perents": "parents",
    "pizz": "pizza",
    "plase": "please",
    "presidant": "president",
    "remmember": "remember",
    "restouront": "restaurant",
    "righg": "right",
    "rightt": "right",
    "sarcasim": "sarcasm",
    "shouldnt": "shouldn't",
    "smae": "same",
    "tbh": "to be honest",
    "thak": "thank",
    "tommorow": "tomorrow",
    "ttyl": "talk to you later",
    "uglt": "ugly",
    "ugy": "ugly",
    "weierd": "weird",
    "whi": "why",
    "whont": "want",
    "wwhats": "what is",
    "yaass": "yes",
    "yeea": "yeah",
    "you'er": "your",
    "nuber": "number",
    "beacause": "because",
    "crieing": "crying",
    "clouns": "clowns",
    "wellcome": "welcome",
    "bout": "about",
    "namr": "name",
    "unnstall": "uninstall",
    "idas": "ideas",
    "cani": "can i",
    "exuse": "excuse",
    "dint": "didn't",
    "possesd": "possessed",
    "mch": "much",
    "latter": "later",
    "areyou": "are you",
    "youare": "you are",
    "wasint": "wasn't",
    "fualt": "fault",
    "awaiy": "away",
    "loveing": "loving",
    "watter": "water",
    "tahts": "that is",
    "tap": "water",
    "plaing": "playing",
    "undderstand": "understand",
    "undestand": "understand",
    "maners": "manners",
    "poope": "poop",
    "tahnk": "thank",
    "femal": "female",
    "helloo": "hello",
    "pizzas": "pizza",
    "ling": "lying",
    "buster's": "busters",
    "leing": "lying",
    "compoter": "computer",
    "sisteror": "sister",
    "durty": "dirty",
    "millon": "million",
    "dallors": "dollars",
    "suk": "suck",
    "lolololololol": "lol",
    "thxs": "thanks",
    "addres": "address",
    "hte": "hate",
    "cahnge": "change",
    "righte": "right",
    "an't": "ain't",
    "tha": "that",
    "pease": "please",
    "boyy": "boy",
    "upto": "up to",
    "favriot": "favorite",
    "talkiong": "talking",
    "nevr": "never",
    "canyou": "can you",
    "si": "is",
    "wateva": "whatever",
    "want 2": "want to",
    "pennis": "penis",
    "hiya": "hi",
    "wnt": "want",
    "freins": "friends",
    "wemeon": "women",
    "heelowwen": "halloween",
    "jully": "july",
    "icant": "i can't",
    "asky": "ask",
    "whts": "what is",
    "whatapp": "what is up",
    "wt": "what",
    "hatr": "hate",
    "phne": "phone",
    "cense": "sense",
    "fone": "phone",
    "elefant": "elephant",
    "geting": "getting",
    "pepeole": "people",
    "garic": "garlic",
    "barr": "bar",
    "boyfrind": "boyfriend",
    "imgay": "i am gay",
    "nme": "name",
    "fucken": "fucking",
    "me 2": "me too",
    "ahve": "have",
    "sisister": "sister",
    "kined": "kind",
    "grilfrend": "girlfriend",
    "imnot": "i am not",
    "wahnt": "want",
    "leav": "leave",
    "haert": "heart",
    "shuldnt": "shouldn't",
    "talikng": "talking",
    "illbe": "i'll be",
    "dousint": "doesn't",
    "gambuling": "gambling",
    "ether": "either",
    "att": "at",
    "ulone": "alone",
    "beacome": "become",
    "willbe": "will be",
    "uther": "other",
    "daiy": "day",
    "lerning": "learning",
    "nighte": "night",
    "gilrs": "girls",
    "outt": "out",
    "yotubers": "youtubers",
    "yotuber": "youtuber",
    "rite": "right",
    "mewwto": "mewtwo",
    "what's": "what is",
    "ghosrt": "ghost",
    "stess": "stress",
    "jobe": "job",
    "lieing": "lying",
    "yyou": "you",
    "peole": "people",
    "truble": "trouble",
    "belve": "believe",
    "girlfrieand": "girlfriend",
    "brok": "broke",
    "nervis": "nervous",
    "wnot": "won't",
    "mistske": "mistake",
    "specheal": "special",
    "minut": "minute",
    "afread": "afraid",
    "bc": "because",
    "surelock": "sherlock",
    "dateing": "dating",
    "sadd": "sad",
    "crazay": "crazy",
    "lul": "lol",
    "smething": "something",
    "birthdate": "birthday",
    "apperance": "appearance",
    "ookay": "ok",
    "anitsocial": "antisocial",
    "fuckyou": "fuck you",
    "gosht": "ghost",
    "haate": "hate",
    "wahts": "what is",
    "amke": "make",
    "werewofs": "werewolves",
    "werewolfs": "werewolves",
    "wolfs": "wolves",
    "goona": "going to",
    "werewof": "werewolf",
    "boyfriendd": "boyfriend",
    "faviorte": "favorite",
    "anderstand": "understand",
    "wereing": "wearing",
    "uoyr": "your",
    "hahahahahahh": "haha",
    "lallalala": "lalala",
    "addreass": "address",
    "hoi": "hi",
    "lonly": "lonely",
    "faggot": "fagot",
    "taliking": "talking",
    "saiy": "say",
    "affter": "after",
    "peniss": "penis",
    "vajina": "vagina",
    "gorjis": "gorgeous",
    "chang": "change",
    "girlfreand": "girlfriend",
    "anough": "enough",
    "doas": "does",
    "lalalala": "lalala",
    "buetifule": "beautiful",
    "hott": "hot",
    "goinna": "going to",
    "3som": "threesome",
    "niigger": "nigger",
    "ladie": "lady",
    "wee": "we",
    "bitchs": "bitch",
    "dieng": "dying",
    "gunna": "going to",
    "resraurant": "restaurant",
    "diong": "doing",
    "ru": "are you",
    "tuch": "touch",
    "dond": "don't",
    "upaligise": "apologise",
    "afrade": "afraid",
    "grilfreind": "girlfriend",
    "yuo": "you",
    "fukin": "fucking",
    "liike": "like",
    "vdf": "wtf",
    "doo": "do",
    "plese": "please",
    "subgec": "subject",
    "bofreind": "boyfriend",
    "weclome": "welcome",
    "neighbror": "neighbour",
    "yoy": "you",
    "poeple": "people",
    "afaired": "afraid",
    "affraid": "afraid",
    "ahh": "oh",
    "ah": "oh",
    "aint": "aren't",
    "aligator": "alligator",
    "alwas": "always",
    "anywere": "anywhere",
    "asshoe": "asshole",
    "athiest": "atheist",
    "aw": "aww",
    "bai": "bye",
    "cause": "because",
    "beause": "because",
    "becuase": "because",
    "belive": "believe",
    "bf": "boyfriend",
    "bicth": "bitch",
    "bich": "bitch",
    "blak": "black",
    "brah": "bro",
    "boyfreind": "boyfriend",
    "boyfrend": "boyfriend",
    "byebye": "bye bye",
    "cant": "can't",
    "colour": "color",
    "coppies": "copies",
    "crazyy": "crazy",
    "dafuq": "wtf",
    "deez": "this",
    "didnt": "didn't",
    "didt": "didn't",
    "difrent": "different",
    "diffrent": "different",
    "diicck": "dick",
    "dont": "don't",
    "duhh": "duh",
    "dum": "dumb",
    "dumm": "dumb",
    "evere": "ever",
    "fav": "favorite",
    "favourite": "favorite",
    "favourtie": "favorite",
    "fb": "facebook",
    "firends": "friends",
    "fo": "for",
    "freind": "friend",
    "frend": "friend",
    "fuk": "fuck",
    "fuq": "fuck",
    "gayy": "gay",
    "genda": "gender",
    "gf": "girlfriend",
    "goaway": "go away",
    "goin": "going",
    "gona": "going to",
    "gonna": "going to",
    "goodby": "goodbye",
    "gramer": "grammar",
    "grammer": "grammar",
    "hai": "hi",
    "hallo": "hello",
    "hant": "haunt",
    "heey": "hey",
    "heyyo": "hey",
    "hei": "hey",
    "he's": "he is",
    "het": "hate",
    "heyy": "hey",
    "hipocrit": "hypocrite",
    "hi5": "hi",
    "hllo": "hello",
    "hm": "hmm",
    "hmph": "hmm",
    "homosexuel": "momosexual",
    "honeey": "honey",
    "hore": "whore",
    "hows": "how is",
    "huh": "what",
    "hy": "hi",
    "chating": "chatting",
    "chines": "chinese",
    "iam": "i am",
    "idk": "i don't know",
    "ik": "i know",
    "im": "i'm",
    "isnt": "isn't",
    "ive": "i have",
    "kida": "kinda",
    "kno": "know",
    "kow": "know",
    "lets": "let's",
    "liek": "like",
    "lil": "little",
    "lmao": "lol",
    "lmfao": "lol",
    "lolipop": "lollipop",
    "lolz": "lol",
    "lool": "lol",
    "lulz": "lol",
    "lulx": "lol",
    "luv": "love",
    "mebey": "maybe",
    "merried": "married",
    "mhm": "hmm",
    "mhmm": "hmm",
    "mm": "hmm",
    "nao": "now",
    "naw": "now",
    "negro": "nigger",
    "niga": "nigger",
    "nigar": "nigger",
    "niger": "nigger",
    "nigga": "nigger",
    "nm": "nevermind",
    "noo": "no",
    "nvm": "nevermind",
    "ohh": "oh",
    "oi": "hey",
    "okay": "ok",
    "o'm": "i'm",
    "o": "oh",
    "ooh": "oh",
    "oo": "oh",
    "opps": "oops",
    "penus": "penis",
    "pic": "picture",
    "pinus": "penis",
    "pizaa": "pizza",
    "piza": "pizza",
    "plz": "please",
    "plzz": "please",
    "poo": "poop",
    "potatos": "potatoes",
    "r": "are",
    "realy": "really",
    "remeber": "remember",
    "respekt": "respect",
    "rofl": "lol",
    "seex": "sex",
    "seexx": "sex",
    "sence": "sense",
    "sext": "sex",
    "she's": "she is",
    "shure": "sure",
    "shyiit": "shit",
    "shiit": "shit",
    "sied": "said",
    "sill": "still",
    "sis": "sister",
    "somehing": "something",
    "soory": "sorry",
    "sould": "should",
    "stupied": "stupid",
    "sup": "what is up",
    "sut": "shut",
    "strait": "straight",
    "thair": "there",
    "thats": "that is",
    "that's": "that is",
    "thx": "thanks",
    "ty": "thank you",
    "uhh": "hmm",
    "uh": "hmm",
    "uhm": "hmm",
    "um": "hmm",
    "umm": "hmm",
    "ur": "your",
    "u": "you",
    "waht": "what",
    "wanna": "want to",
    "wan't": "want",
    "wassup": "what is up",
    "wat": "what",
    "we're": "we are",
    "whats": "what is",
    "wheres": "where is",
    "whhats": "what is",
    "whoah": "whoa",
    "whoops": "oops",
    "who's": "who is",
    "whou": "whoa",
    "wht": "what",
    "whut": "what",
    "whu": "who",
    "withh": "with",
    "wont": "won't",
    "woops": "oops",
    "wrud": "what are you doing",
    "wth": "wtf",
    "wut": "what",
    "xd": "lol",
    "ya": "you",
    "yeas": "yes",
    "yea": "yeah",
    "yep": "yeah",
    "yess": "yes",
    "youre": "you're",
    "your'e": "you're",
    "your's": "yours",
    "yo": "your",
    "yup": "yeah",
    "y": "why",
    "aganst": "against",
    "dose": "does",
    "frening": "friend",
    "acn": "can",
    "booring": "boring",
    "gess": "guess",
    "deleteing": "deleting",
    "sighn": "sign",
    "helow": "hello",
    "cuz": "because",
    "vedio": "video",
    "weeken": "weekend",
    "chiristan": "christian",
    "mabye": "maybe",
    "thios": "this",
    "lel": "lol",
    "bruh": "bro",
    "fave": "favorite",
    "meh": "me",
    "ppl": "people",
    "suscribe": "subscribe",
    "whers": "where is",
    "swere": "swear",
    "whereing": "wearing",
    "yuou": "you",
    "youn": "you",
    "spansh": "spanish",
    "speek": "speak",
    "gud": "good",
    "yah": "yeah",
    "stuped": "stupid",
    "byee": "bye",
    "reel": "real",
    "awsome": "awesome",
    "uo": "up",
    "pritty": "pretty",
    "whant": "want",
    "tacking": "taking",
    "shcool": "school",
    "wheni": "when i",
    "trobel": "trouble",
    "wuv": "love",
    "kewl": "cool",
    "anythiing": "anything",
    "basicly": "basically",
    "elphant": "elephant",
    "sry": "sorry",
    "babay": "baby",
    "doin": "doing",
    "fucku": "fuck you",
    "bitc": "bitch",
    "ideot": "idiot",
    "imon": "i'm on",
    "dcik": "dick",
    "k": "ok",
    "swaer": "swear",
    "iluminati": "illuminati",
    "depress": "depressed",
    "angainst": "against",
    "hoe": "whore",
    "thougth": "thought",
    "basicaly": "basically",
    "pea": "pee",
    "lier": "liar",
    "bith": "bitch",
    "chiken": "chicken",
    "gost": "ghost",
    "ben": "been",
    "creppy": "creepy",
    "let`s": "let's",
    "that`s": "that is",
    "sceard": "scared",
    "wathing": "watching",
    "myname": "my name",
    "crazey": "crazy",
    "youa": "you a",
    "coled": "called",
    "shoru": "sure",
    "dount": "don't",
    "goast": "ghost",
    "werid": "weird",
    "wierd": "weird",
    "nastey": "nasty",
    "girlfrined": "girlfriend",
    "yoru": "your",
    "niht": "night",
    "sexs": "sex",
    "scool": "school",
    "creapo": "creep",
    "syalker": "stalker",
    "lest": "last",
    "whens": "when is",
    "ike": "like",
    "wegh": "weight",
    "eather": "either",
    "don": "done",
    "meany": "mean",
    "daiting": "dating",
    "yya": "yeah",
    "weiring": "wearing",
    "chese": "cheese",
    "rasist": "racist",
    "yu": "you",
    "rally": "really",
    "asnwer": "answer",
    "wats": "what is",
    "fealing": "feeling",
    "dunp": "dump",
    "nok": "ok",
    "hwo": "who",
    "unkcle": "uncle",
    "makeing": "making",
    "luch": "lunch",
    "myne": "mine",
    "neflxe": "netflix",
    "mornig": "morning",
    "caee": "care",
    "xmas": "christmas",
    "ii": "i",
    "etherr": "either",
    "dosent": "doesn't",
    "dosn't": "doesn't",
    "huant": "haunt",
    "yall": "you all",
    "nop": "nope",
    "deeznuts": "this nuts",
    "fukyou": "fuck you",
    "mabe": "maybe",
    "pleas": "please",
    "problaby": "probably",
    "soo": "so",
    "thankyou": "thank you",
    "whay": "why",
    "yew": "you",
    "ar": "are",
    "werd": "weird",
    "likeed": "liked",
    "ghg": "gtg",
    "heez": "geez",
    "ayy": "yeah",
    "nutz": "nuts",
    "fck": "fuck",
    "constert": "concert",
    "expeiriens": "experience",
    "deinstall": "uninstall",
    "iceream": "icecream",
    "vchat": "video chat",
    "tomarow": "tomorrow",
    "b-day": "birthday",
    "bday": "birthday",
    "languge": "language",
    "lama": "llama",
    "hoex": "hoax",
    "<3": "love",
    "me2": "me too",
    "seoseon": "session",
    "threm": "them",
    "arent": "aren't",
    "cromebook": "chromebook",
    "hqate": "hate",
    "whatup": "what is up",
    "biatchh": "bitch",
    "thaught": "thought",
    "hellow": "hello",
    "yrea": "yeah",
    "fantisize": "fantasize",
    "bak": "back",
    "titties": "boobs",
    "dam": "damn",
    "wasnt": "wasn't",
    "imortal": "immortal",
    "dangit": "damn it",
    "supp": "what is up",
    "purose": "purpose",
    "tghis": "this",
    "oyu": "you",
    "thanx": "thanks",
    "muslum": "muslim",
    "moslum": "muslim",
    "moslim": "muslim",
    "nuthing": "nothing",
    "leving": "leaving",
    "sistetr": "sister",
    "fuking": "fucking",
    "penes": "penis",
    "stupide": "stupid",
    "da": "do",
    "lkie": "like",
    "you'r": "you are",
    "sleppin": "sleeping",
    "helpp": "help",
    "mee": "me",
    "boredum": "boredom",
    "opkayy": "ok",
    "okayy": "ok",
    "how-so": "how so",
    "bish": "bitch",
    "ima": "i'm a",
    "wby": "why",
    "hii": "hi",
    "basturd": "bastard",
    "oomg": "omg",
    "dou": "do",
    "al": "all",
    "youu": "you",
    "omh": "omg",
    "srry": "sorry",
    "achoo": "atchoo",
    "crapo": "crap",
    "dosen't": "doesn't",
    "mabey": "maybe",
    "seein": "seeing",
    "whta": "what",
    "yer": "you are",
    "meanig": "meaning",
    "meanin": "meaning",
    "heyo": "hey",
    "bitches": "bitch",
    "murica": "america",
    "els": "else",
    "statment": "statement",
    "michine": "machine",
    "c": "see",
    "tthey": "they",
    "riel": "real",
    "somethig": "something",
    "udumb": "dumb",
    "frid": "friend",
    "becase": "because",
    "bla": "blah",
    "blea": "blah",
    "btw": "by the way",
    "thoe": "tho",
    "wuz": "was",
    "deeznutz": "this nuts",
    "dfq": "wtf",
    "likw": "like",
    "wan": "want",
    "ew": "eew",
    "goodmorning": "good morning",
    "hahahha": "haha",
    "hahaha": "haha",
    "hahahaha": "haha",
    "hahahahaha": "haha",
    "hahahahahaha": "haha",
    "hahahahahahaha": "haha",
    "hahah": "haha",
    "hahahah": "haha",
    "hahahahah": "haha",
    "hahahahahah": "haha",
    "hahahahahahah": "haha",
    "hahahahahahahah": "haha",
    "ahah": "haha",
    "ahahah": "haha",
    "ahahahah": "haha",
    "ahahahahah": "haha",
    "ahahahahahah": "haha",
    "ahahahahahahah": "haha",
    "ahaha": "haha",
    "ahahaha": "haha",
    "ahahahaha": "haha",
    "ahahahahaha": "haha",
    "ahahahahahaha": "haha",
    "ahahahahahahaha": "haha",
    "hihi": "haha",
    "hihihi": "haha",
    "hihihihi": "haha",
    "hihihihihi": "haha",
    "hihihihihihi": "haha",
    "latley": "lately",
    "sleepey": "sleepy",
    "fuckin": "fucking",
    "chacalate": "chocolate",
    "yoiu": "you",
    "falt": "fault",
    "wsant": "wasn't",
    "stong": "strong",
    "whioch": "which",
    "sp00ky": "spooky",
    "cri": "cry",
    "evry": "every",
    "tim": "time",
    "yur": "your",
    "fals": "falls",
    "de": "the",
    "flor": "floor",
    "meanj": "mean",
    "whaa": "what",
    "somtimes": "sometimes",
    "wen": "when",
    "saton": "satan",
    "yout": "you",
    "youmarried": "you married",
    "buruh": "bro",
    "fuckboi": "fuck boy",
    "likr": "like",
    "fetishe": "fetish",
    "realyy": "really",
    "upp": "up",
    "idoit": "idiot",
    "rember": "remember",
    "koolo": "cool",
    "yeh": "yeah",
    "ice-cream": "ice cream",
    "didyou": "did you",
    "scholl": "school",
    "actuall": "actual",
    "prestley": "presley",
    "laught": "laugh",
    "whath": "what",
    "pusy": "pussy",
    "ye": "yeah",
    "aare": "are",
    "creept": "creepy",
    "nowone": "no one",
    "meaj": "mean",
    "how's": "how is",
    "i'll": "i will",
    "haev": "have",
    "where's": "where is",
    "laughting": "laughing",
    "diveded": "divided",
    "icecraem": "ice cream",
    "wassupp": "what is up",
    "watchya": "what you are",
    "tht": "that",
    "ikr": "i know right",
    "cource": "course",
    "wha": "what",
    "whichis": "which is",
    "vagin": "vagina",
    "whateveah": "whatever",
    "ook": "ok",
    "namw": "name",
    "till": "until",
    "funn": "fun",
    "wtff": "wtf",
    "hru": "how are you",
    "inlove": "in love",
    "wusup": "what is up",
    "shup": "shut",
    "cholate": "chocolate",
    "anouther": "another",
    "woill": "will",
    "shes": "she is",
    "waching": "watching",
    "yee": "yeah",
    "grampa": "grandpa",
    "duummbb": "dumb",
    "anser": "answer",
    "qeashtoin": "question",
    "plee": "please",
    "kknnoow": "know",
    "iit": "it",
    "girlfreind": "girlfriend",
    "beye": "bye",
    "humen": "human",
    "tis": "this",
    "helloi": "hello",
    "eh": "he",
    "bieng": "being",
    "guss": "guess",
    "chistmas": "christmas",
    "can;t": "can't",
    "hunry": "hungry",
    "lastnite": "last night",
    "emm": "hmm",
    "looser": "loser",
    "allways": "always",
    "colm": "calm",
    "bypolur": "bipolar",
    "likkes": "likes",
    "namee": "name",
    "ehh": "hmm",
    "ontile": "until",
    "i m": "i am",
    "goiing": "going",
    "huunt": "hunt",
    "ugle": "ugly",
    "famile": "family",
    "aethiast": "atheist",
    "againts": "against",
    "awfull": "awful",
    "billingual": "bilingual",
    "buttler": "butler",
    "callet": "called",
    "cancelled": "canceled",
    "cortanna": "cortana",
    "honney": "honey",
    "choosed": "choose",
    "it't": "it is",
    "beacuse": "because",
    "beging": "begging",
    "definetely": "definitely",
    "acoording": "according",
    "youi": "you",
    "boi": "boy",
    "scarey": "scary",
    "havent": "haven't",
    "flavor": "flavour",
    "did'nt": "didn't",
    "deffinetly": "definitely",
    "fisheman": "fisherman",
    "howie": "howdy",
    "meaningfull": "meaningful",
    "ment": "meant",
    "moorning": "morning",
    "m8": "mate",
    "preffer": "prefer",
    "proove": "prove",
    "proov": "prove",
    "sayin": "saying",
    "theese": "these",
    "til": "until",
    "loozer": "loser",
    "loozers": "losers",
    "loosers": "losers",
    "genious": "genius",
    "alot": "a lot",
    "ghots": "ghost",
    "gezz": "geez",
    "tf": "the fuck",
    "ds": "this",
    "gotta": "have got",
    "byw": "bye",
    "orentation": "orientation",
    "wondeful": "wonderful",
    "beautifull": "beautiful",
    "yr": "your",
    "pepole": "people",
    "akward": "awkward",
    "dragonballz": "dragonball z",
    "thoose": "those",
    "sas": "sass",
    "kiding": "kidding",
    "chrisitan": "christian",
    "chrisitans": "christians",
    "apologizing": "apologising",
    "apologize": "apologise",
    "whm": "hmm",
    "masterbate": "masturbate",
    "humal": "human",
    "iww": "eew",
    "awesom": "awesome",
    "bithc": "bitch",
    "ghosst": "ghost",
    "yeeah": "yeah",
    "urself": "yourself",
    "deid": "died",
    "oww": "aww",
    "yap": "yeah",
    "brthday": "birthday",
    "yas": "yes",
    "yeaa": "yeah",
    "fatt": "fat",
    "adout": "about",
    "scfew": "screw",
    "wev": "we have",
    "favoriate": "favorite",
    "thier": "their",
    "cuase": "because",
    "mame": "name",
    "siad": "said",
    "yeahh": "yeah",
    "blahh": "blah",
    "exsakle": "exactly",
    "idc": "i don't care",
    "aboy": "a boy",
    "chickenn": "chicken",
    "h8": "hate",
    "disinstall": "uninstall",
    "freinds": "friends",
    "faviriot": "favorite",
    "buissness": "business",
    "bussines": "business",
    "awnesering": "answering",
    "mirrior": "mirror",
    "ypu": "you",
    "sux": "sucks",
    "doyou": "do you",
    "awayls": "always",
    "thoes": "those",
    "rong": "wrong",
    "choclate": "chocolate",
    "ageain": "again",
    "whatt": "what",
    "tommrow": "tomorrow",
    "w8": "wait",
    "suc": "suck",
    "retarted": "retarded",
    "favoirte": "favorite",
    "yass": "yes",
    "pls": "please",
    "goodnight": "good night",
    "goodd": "good",
    "hungery": "hungry",
    "we'll": "we will",
    "babbys": "babies",
    "babys": "babies",
    "realname": "real name",
    "wortst": "worst",
    "whatevs": "whatever",
    "hes": "he is",
    "vaginu": "vagina",
    "nothen": "nothing",
    "marrie": "marry",
    "knw": "know",
    "saracasim": "sarcasm",
    "machin": "machine",
    "adress": "address",
    "jeark": "jerk",
    "helo": "hello",
    "daa": "duh",
    "woah": "whoa",
    "wooah": "whoa",
    "acttuly": "actually",
    "thaks": "thanks",
    "beutiful": "beautiful",
    "riely": "really",
    "wana": "want to",
    "weding": "wedding",
    "informashon": "information",
    "dodnt": "didn't",
    "compture": "computer",
    "coures": "course",
    "blive": "believe",
    "omgg": "omg",
    "choclet": "chocolate",
    "wasent": "wasn't",
    "we've": "we have",
    "bie": "bye",
    "rely": "really",
    "haveing": "having",
    "maarry": "marry",
    "forgivee": "forgive",
    "sistr": "sister",
    "wantz": "wants",
    "sckool": "school",
    "relly": "really",
    "scred": "scared",
    "thnx": "thanks",
    "glases": "glasses",
    "nnoo": "no",
    "mmhm": "hmm",
    "favour": "favor",
    "okie": "ok",
    "sucide": "suicide",
    "resturant": "restaurant",
    "hawe": "have",
    "somone": "someone",
    "bicicle": "bicycle",
    "brocoli": "broccoli",
    "broccolli": "broccoli",
    "brocolli": "broccoli",
    "skool": "school",
    "birthay": "birthday",
    "okey": "ok",
    "urs": "yours",
    "deamon": "demon",
    "damon": "demon",
    "oposite": "opposite",
    "duing": "doing",
    "wher": "where",
    "betr": "better",
    "mebe": "maybe",
    "yaay": "yay",
    "you'd": "you would",
    "videogame": "video game",
    "snowbording": "snowboarding",
    "rea[eat": "repeat",
    "ouiji": "ouija",
    "dieing": "dying",
    "pregnat": "pregnant",
    "numbeer": "number",
    "yello": "hello",
    "whaching": "watching",
    "truu": "true",
    "pregnate": "pregnant",
    "iz": "is",
    "h3llo": "hello",
    "cmon": "come on",
    "programed": "programmed",
    "g2g": "i have to go",
    "how're": "how are",
    "kk": "ok",
    "tomorow": "tomorrow",
    "convo": "conversation",
    "happend": "happened",
    "fravorite": "favorite",
    "pupies": "puppies",
    "asf": "as fuck",
    "nock": "knock",
    "hak": "hack",
    "hapy": "happy",
    "h3h3h3": "hehe",
    "abuot": "about",
    "flaver": "flavour",
    "hhii": "hi",
    "favrorite": "favorite",
    "gohst": "ghost",
    "preganant": "pregnant",
    "pregannt": "pregnant",
    "mutch": "much",
    "lassagna": "lasagna",
    "lasagne": "lasagna",
    "nvrm": "nevermind",
    "stuiped": "stupid",
    "reaally": "really",
    "wot": "what",
    "wyd": "what are you doing",
    "attiude": "attitude",
    "wassaap": "what is up",
    "noice": "nice",
    "lalalalalala": "la la la",
    "claver": "clever",
    "maby": "maybe",
    "boyfrinde": "boyfriend",
    "frinde": "friend",
    "beter": "better",
    "cheeted": "cheated",
    "kool": "cool",
    "nether": "neither",
    "parentes": "parents",
    "sandvich": "sandwich",
    "dumpet": "dumped",
    "hateed": "hated",
    "befor": "before",
    "troble": "trouble",
    "cromebooks": "chromebooks",
    "bfreind": "boyfriend",
    "handsom": "handsome",
    "delet": "delete",
    "promis": "promise",
    "eny": "any",
    "frends": "friends",
    "arnt": "aren't",
    "anrnt": "aren't",
    "stopid": "stupid",
    "wunt": "want",
    "pregnet": "pregnant",
    "weigh": "weight",
    "flovaor": "flavour",
    "deomon": "demon",
    "spong": "sponge",
    "beleave": "believe",
    "bllack": "black",
    "yyour": "your",
    "gilr": "girl",
    "cannt": "cannot",
    "illuminotii": "illuminati",
    "uglyy": "ugly",
    "scery": "scary",
    "radomly": "randomly",
    "ansering": "answering",
    "gurls": "girls",
    "girlfreaind": "girlfriend",
    "girlfraeind": "girlfriend",
    "sleping": "sleeping",
    "theyre": "they are",
    "neather": "neigher",
    "kis": "kiss",
    "wieght": "weight",
    "illumianati": "illuminati",
    "cartton": "cartoon",
    "netwerk": "network",
    "bcuase": "because",
    "docter": "doctor",
    "ghoost": "ghost",
    "u'r": "you are",
    "wayd": "what are you doing",
    "fater": "father",
    "childerin": "children",
    "tomaroww": "tomorrow",
    "htta": "that",
    "progam": "program",
    "jokeing": "joking",
    "thts": "that is",
    "schol": "school",
    "wnat": "want",
    "ghist": "ghost",
    "gohost": "ghost",
    "whre": "where",
    "beacouse": "because",
    "lic": "lick",
    "comeing": "coming",
    "comming": "coming",
    "crismas": "christmas",
    "wering": "wearing",
    "somthin": "something",
    "becaus": "because",
    "gfreind": "girlfriend",
    "loove": "love",
    "everday": "everyday",
    "coloar": "color",
    "diveided": "divided",
    "favroite": "favorite",
    "funnest": "funniest",
    "hwta": "what",
    "yiu": "you",
    "pikcher": "picture",
    "kiiss": "kiss",
    "stoopid": "stupid",
    "boyfraind": "boyfriend",
    "boyfreaind": "boyfriend",
    "chage": "change",
    "fraind": "friend",
    "borad": "bored",
    "aa": "a",
    "whho": "who",
    "thoese": "those",
    "gr8": "great",
    "ulgy": "ugly",
    "completeley": "completely",
    "friens": "friend",
    "hahahahhaha": "haha",
    "stuoid": "stupid",
    "atheiste": "atheist",
    "atheiest": "atheist",
    "nervouse": "nervous",
    "beleive": "believe",
    "buteful": "beautiful",
    "somthing": "something",
    "faverit": "favorite",
    "favorie": "favorite",
    "restrant": "restaurant",
    "freynd": "friend",
    "yhae": "yeah",
    "bff": "best friend forever",
    "sori": "sorry",
    "were is": "where is",
    "nono": "no no",
    "faourite": "favorite",
    "faorite": "favorite",
    "fauvorite": "favorite",
    "exqus": "excuse",
    "porpose": "purpose",
    "l8er": "later",
    "ghoast": "ghost",
    "takeing": "taking",
    "minecarft": "minecraft",
    "girlfirnd": "girlfriend",
    "byyee": "bye",
    "freindly": "friendly",
    "favoite": "favorite",
    "ferget": "forget",
    "copping": "copying",
    "bootiful": "beautiful",
    "goodnigt": "good night",
    "givee": "give",
    "'m": "am",
    "how 2": "how to",
    "you tube": "youtube",
    "need 2": "need to",
    "girlfriand": "girlfriend",
    "ghay": "gay",
    "swiming": "swimming",
    "havit": "have it",
    "prson": "person",
    "yuor": "your",
    "mamas": "mama is",
    "felling": "feeling",
    "fellings": "feelings",
    "thouht": "thought",
    "starwars": "star wars",
    "java script": "javascript",
    "resteraunt": "restaurant",
    "frind": "friend",
    "creazy": "crazy",
    "a bout": "about",
    "wazup": "what is up",
    "minecaft": "minecraft",
    "braking": "breaking",
    "persanal": "personal",
    "brocli": "broccoli",
    "brocili": "broccoli",
    "brocali": "broccoli",
    "pitcure": "picture",
    "shold": "should",
    "masterbait": "masturbate",
    "wwhere": "where",
    "kild": "killed",
    "ghos": "ghost",
    "becuse": "because",
    "faverite": "favorite",
    "srsly": "seriously",
    "aer": "are",
    "out side": "outside",
    "aqward": "awkward",
    "ghostie": "ghost",
    "lasange": "lasagna",
    "girll": "girl",
    "fagit": "fagot",
    "broccoil": "broccoli",
    "vhaginay": "vagina",
    "sourse": "source",
    "chaterbot": "chat bot",
    "hlp": "help",
    "okk": "ok",
    "howz": "how is",
    "creater": "creator",
    "happt": "happy",
    "hobys": "hobbies",
    "preagnant": "pregnant",
    "poultergiest": "poltergeist",
    "specail": "special",
    "kpop": "k-pop",
    "jpop": "j-pop",
    "butiful": "beautiful",
    "broccli": "broccoli",
    "marrige": "marriage",
    "divorse": "divorce",
    "thnks": "thanks",
    "basket ball": "basketball",
    "jk": "just kidding",
    "beatiful": "beautiful",
    "i've": "i have",
    "marred": "married",
    "cheter": "cheater",
    "ihy": "i hate you",
    "goodbyye": "goodbye",
    "whtas": "what is",
    "favrouit": "favorite",
    "wrongg": "wrong",
    "agin": "again",
    "likke": "like",
    "tallk": "talk",
    "becoause": "because",
    "animail": "animal",
    "happiness": "happines",
    "areu": "are you",
    "guesse": "guess",
    "naame": "name",
    "juses": "jesus",
    "talkitve": "talkative",
    "midgit": "midget",
    "tauch": "touch",
    "frieds": "friends",
    "mena": "mean",
    "lets's": "let's",
    "wiegh": "weight",
    "weighe": "weight",
    "computrr": "computer",
    "thankn": "thank",
    "makout": "makeout",
    "emojie": "emoji",
    "llook": "look",
    "rght": "right",
    "dumbie": "dumb",
    "ughh": "ugh",
    "supries": "surprise",
    "dumass": "dumbass",
    "yung": "young",
    "clube": "club",
    "hahahaa": "haha",
    "chrismas": "christmas",
    "cryid": "cried",
    "haker": "hacker",
    "chinkn": "chicken",
    "resons": "reasons",
    "wemen": "women",
    "reale": "real",
    "stupidd": "stupid",
    "preety": "pretty",
    "pitcher": "picture",
    "schoo": "school",
    "moives": "movies",
    "bitchh": "bitch",
    "cya": "see you",
    "lahfing": "laughing",
    "ancer": "answer",
    "waliking": "walking",
    "daiys": "days",
    "farrt": "fart",
    "freindy": "friendly",
    "belave": "believe",
    "lov": "love",
    "praiy": "pray",
    "angery": "angry",
    "angy": "angry",
    "cumputer": "computer",
    "nwe": "new",
    "boyfreing": "boyfriend",
    "freinf": "friend",
    "askinkg": "asking",
    "docters": "doctor's",
    "hostpital": "hospital",
    "hopsital": "hospital",
    "hopital": "hospital",
    "hospitsl": "hospital",
    "hosptal": "hospital",
    "wellocme": "welcome",
    "hposital": "hospital",
    "cal": "call",
    "aquare": "square",
    "watchin": "watching",
    "waiy": "way",
    "frist": "first",
    "nott": "not",
    "ganna": "going to",
    "donnt": "don't",
    "womean": "woman",
    "calcularot": "calculator",
    "yeepp": "yeah",
    "bridfe": "bridge",
    "whatevveerr": "whatever",
    "notin": "nothing",
    "wft": "wtf",
    "wellcom": "welcome",
    "elementry": "elementary",
    "danceing": "dancing",
    "myshlef": "myself",
    "frendes": "friends",
    "famliy": "family",
    "ghoust": "ghost",
    "favthing": "favorite thing",
    "watu": "what you",
    "devided": "divided",
    "roodust": "rudest",
    "suff": "stuff",
    "changeing": "changing",
    "sur": "sure",
    "wiht": "with",
    "gfrielnd": "girlfriend",
    "ther": "there",
    "idot": "idiot",
    "repect": "respect",
    "rihte": "right",
    "cloths": "clothes",
    "wdym": "what do you mean",
    "bu": "boo",
    "agly": "ugly",
    "amarica": "america",
    "amaziong": "amazing",
    "babby": "baby",
    "bannana": "banana",
    "borring": "boring",
    "boyriend": "boyfriend",
    "breakfist": "breakfast",
    "bullyed": "bullied",
    "cann": "can",
    "chickem": "chicken",
    "chocalate": "chocolate",
    "christion": "christian",
    "damit": "damnit",
    "dammit": "damnit",
    "dnt": "don't",
    "dont't": "don't",
    "donut": "doughnut",
    "dounuts": "doughnuts",
    "ello": "hello",
    "favotite": "favorite",
    "firend": "friend",
    "foreal": "for real",
    "frined": "friend",
    "frm": "from",
    "ghst": "ghost",
    "gostbuster": "ghostbuster",
    "hallowween": "halloween",
    "hangry": "i'm",
    "hansome": "handsome",
    "happns": "happens",
    "heloo": "hello",
    "hiy": "hi",
    "hous": "house",
    "husbend": "husband",
    "idgaf": "i don't care",
    "igtg": "i got to go",
    "invisable": "invisible",
    "kmow": "know",
    "l'm": "i am",
    "lonley": "lonely",
    "machins": "machines",
    "marrage": "marriage",
    "marrieed": "married",
    "mather": "mother",
    "meen": "mean",
    "mum": "mom",
    "noyses": "noises",
    "obviuosly": "obviously",
    "ookk": "ok",
    "outsde": "outside",
    "oyur": "your",
    "pickachu": "pikachu",
    "politcs": "politics",
    "pregent": "pregnant",
    "pregnaut": "pregnant",
    "pregnut": "pregnant",
    "prety": "pretty",
    "prisedent": "president",
    "rblox": "roblox",
    "reeally": "really",
    "religon": "religion",
    "rellay": "really",
    "rnumber": "number",
    "scard": "scared",
    "serioues": "serious",
    "singl": "single",
    "siting": "sitting",
    "someoen": "someone",
    "ssorry": "sorry",
    "stipid": "stupid",
    "sttupid": "stupid",
    "stupi": "stupid",
    "sumone": "someone",
    "surpise": "surprise",
    "teday": "today",
    "toilt": "toilet",
    "tomoorow": "tomorrow",
    "touchhing": "touching",
    "waant": "want",
    "wach": "watch",
    "whith": "with",
    "whiy": "why",
    "yey": "yay",
    "yor": "your",
    "youll": "you will",
    "yuour": "your",
    "girlfrind": "girlfriend",
    "actully": "actually",
    "zealnad": "zealand",
    "noway": "no way",
    "boyfreand": "boyfriend",
    "ae": "are",
    "aweome": "awesome",
    "borading": "boarding",
    "boyfirend": "boyfriend",
    "broher": "brother",
    "chrimas": "christmas",
    "coping": "copying",
    "deffinatly": "definitely",
    "depressd": "depressed",
    "emal": "email",
    "eneybody": "anybody",
    "fase": "face",
    "greade": "grade",
    "groosest": "grossest",
    "i;m": "i'm",
    "leasbian": "lesbian",
    "peopel": "people",
    "prents": "parents",
    "qustion": "question",
    "satruday": "saturday",
    "sexxy": "sexy",
    "thnkx": "thanks",
    "watever": "whatever",
    "what're": "what are",
    "wwhat": "what",
    "yayy": "yay",
    "yeess": "yes",
    "youur": "your",
    "youz": "you",
    "ai't": "ain't",
    "alredy": "already",
    "badword": "bad word",
    "baskit": "basket",
    "bcause": "because",
    "beleve": "believe",
    "brocalli": "broccoli",
    "broed": "bored",
    "bru": "bro",
    "bruhh": "bro",
    "bsy": "busy",
    "cecret": "secret",
    "chatbox": "chat bot",
    "clas": "class",
    "congrats": "congratulation",
    "correcto": "correct",
    "csnt": "can't",
    "earase": "erase",
    "eeww": "eew",
    "elephangts": "elephants",
    "evr": "ever",
    "evrething": "everything",
    "familt": "family",
    "favirt": "favorite",
    "frinds": "friends",
    "frirnds": "friends",
    "funy": "funny",
    "gangters": "gangsters",
    "ghosh": "ghost",
    "girlfried": "girlfriend",
    "gosts": "ghosts",
    "grlifrind": "girlfriend",
    "haave": "have",
    "haw": "how",
    "haws": "house",
    "hobbys": "hobbies",
    "howold": "how old",
    "hullo": "hello",
    "idfc": "i don't care",
    "idrc": "i don't really care",
    "ily": "i love you",
    "kanichiwa": "konnichiwa",
    "kenichiwa": "konnichiwa",
    "likee": "like",
    "liveing": "living",
    "m3d": "mad",
    "maread": "married",
    "marryed": "married",
    "mechine": "machine",
    "meey": "meet",
    "namoe": "name",
    "nexr": "next",
    "nicd": "nice",
    "nmae": "name",
    "nmber": "number",
    "nnot": "not",
    "noothing": "nothing",
    "nudez": "nudes",
    "omgle": "omegle",
    "pelas": "please",
    "persone": "person",
    "raciset": "racist",
    "raelly": "really",
    "reallt": "really",
    "reapiting": "repeating",
    "rud": "rude",
    "secert": "secret",
    "sicsors": "scissors",
    "skanck": "skank",
    "slepping": "sleeping",
    "smmer": "summer",
    "sometig": "something",
    "stupit": "stupid",
    "taht": "that",
    "tajmahal": "taj mahal",
    "thanxs": "thanks",
    "thenk": "thank",
    "thnxs": "thanks",
    "thoght": "thought",
    "tine": "time",
    "tolld": "told",
    "tusday": "tuesday",
    "twll": "tell",
    "waddup": "what is up",
    "wasupp": "what is up",
    "wernt": "weren't",
    "whit": "with",
    "wjat": "what",
    "woww": "wow",
    "yeahhaa": "yeah",
    "yoou": "you",
    "fireman": "firefighter",
    "christain": "christian",
    "controll": "control",
    "creatd": "created",
    "exsist": "exist",
    "gomenasai": "gomennasai",
    "hobbie": "hobby",
    "instragram": "instagram",
    "konnchiwa": "konnichiwa",
    "musicall": "musical",
    "rea": "real",
    "smrt": "smart",
    "thanls": "thanks",
    "tnx": "thanks",
    "wazzuupp": "what is up",
    "wich": "which",
    "yoouu": "you",
    "abd": "bad",
    "bcome": "become",
    "bcos": "because",
    "bcose": "because",
    "chatimg": "chatting",
    "doesnt": "doesn't",
    "don;t": "don't",
    "foreever": "forever",
    "frnds": "friends",
    "girlfrienf": "girlfriend",
    "gtting": "getting",
    "hman": "human",
    "jjust": "just",
    "jok": "joke",
    "lama's": "llamas",
    "lamas": "llamas",
    "problm": "problem",
    "problms": "problems",
    "spirets": "spirits",
    "thanq": "thank",
    "thnq": "thank",
    "trll": "tell",
    "welcom": "welcome",
    "pichr": "picture",
    "pippl": "people",
    "thans": "thanks",
    "thnxx": "thanks",
    "gratefull": "grateful",
    "marijuana": "marihuana",
    "there's": "there is",
    "talkigg": "talking",
    "a'm": "am",
    "awesomee": "awesome",
    "definitly": "definitely",
    "icecram": "ice cream",
    "knoc": "knock",
    "licence": "license",
    "lisence": "license",
    "lttle": "little",
    "macine": "machine",
    "maebe": "maybe",
    "pu$$y": "pussy",
    "sonthig": "something",
    "thare": "there",
    "wory": "worry",
    "antil": "until",
    "firetruck": "fire truck",
    "raisist": "racist",
    "rly": "really",
    "frienf": "friend",
    "pleasse": "please",
    "3at": "eat",
    "hwy": "why",
    "asswhole": "asshole",
    "criying": "crying",
    "evrything": "everything",
    "notjing": "nothing",
    "oopse": "oops",
    "wamt": "want",
    "woorms": "worms",
    "wehre": "where",
    "beacasu": "because",
    "dosnt": "doesn't",
    "slwwpp": "sleep",
    "donot": "don't",
    "houes": "house",
    "shrodinger": "schrodinger",
    "shrodingers": "schrodingers",
    "shrodinger's": "schrodinger's",
    "timw": "time",
    "ghpst": "ghost",
    "gudnight": "good night",
    "injurned": "injured",
    "reall": "real",
    "wasteing": "wasting",
    "wherw": "where",
    "wwhy": "why",
    "aunty": "aunt",
    "fighet": "fidget",
    "glibberish": "gibberish",
    "morher": "mother",
    "mothrf": "mother",
    "spiner": "spinner",
    "suckk": "suck",
    "sutch": "such",
    "thanxx": "thanks",
    "tjen": "then",
    "uninstal": "uninstall",
    "xhicken": "chicken",
    "chatt": "chat",
    "hay": "hey",
    "perv": "pervert",
    "smatr": "smart",
    "youwant": "you want",
    "thn": "then",
    "andestand": "understand",
    "coe": "cow",
    "hyy": "hi",
    "knockknock": "knock knock",
    "averything": "everything",
    "dinosaus": "dinosaurs",
    "drkness": "darkness",
    "is'nt": "isn't",
    "marrief": "married",
    "naaw": "no",
    "noe": "now",
    "olso": "also",
    "plss": "please",
    "sisguisting": "disgusting",
    "uour": "your",
    "woaah": "whoa",
    "yeaah": "yeah",
    "advixe": "advice",
    "allive": "alive",
    "annoyin": "annoying",
    "arw": "are",
    "becoz": "because",
    "coulour": "color",
    "diid": "did",
    "enoguht": "enough",
    "faild": "failed",
    "fakr": "fake",
    "gamrs": "games",
    "girkl": "girl",
    "holloween": "halloween",
    "humann": "human",
    "isit": "is it",
    "mareid": "married",
    "nothin": "nothing",
    "repear": "repair",
    "samrt": "smart",
    "samw": "same",
    "similer": "similar",
    "luckt": "lucky",
    "frnd": "friend",
    "sonething": "something",
    "thankz": "thanks",
    "tommarow": "tomorrow",
    "boyfrien": "boyfriend",
    "inglish": "english",
    "intelligient": "intelligent",
    "ita": "it is",
    "somwone": "someone",
    "sweeti": "sweetie",
    "whqt": "what",
    "sicl": "sick",
    "sothing": "something",
    "tupid": "stupid",
    "dumy": "dummy",
    "eggsactly": "exactly",
    "imagenary": "imaginary",
    "intence": "intense",
    "iy": "it",
    "kknow": "know",
    "knpw": "know",
    "mwwt": "meet",
    "nlt": "not",
    "popose": "purpose",
    "repetetive": "repetitive",
    "saiyng": "saying",
    "stomick": "stomach",
    "wahtever": "whatever",
    "whatis": "what is",
    "yiou": "you",
    "couldnt": "couldn't",
    "wat's": "what is",
    "heres": "here is",
    "rinf": "ring",
    "basmente": "basement",
    "cheast": "chest",
    "dus": "does",
    "hreb": "herb",
    "medasen": "medicine",
    "meidasan": "medicine",
    "nedds": "needs",
    "cemetary": "cemetery",
    "hellp": "help",
    "thakns": "thanks",
    "wll": "will",
    "nkow": "know",
    "sellfesh": "selfish",
    "coll": "cool",
    "anme": "name",
    "biuldings": "buildings",
    "emrald": "emerald",
    "gve": "give",
    "howd": "how did",
    "machien": "machine",
    "mediceine": "medicine",
    "qeust": "quest",
    "thnak": "thank",
    "babr": "babe",
    "artifitial": "artificial",
    "c00l": "cool",
    "elsr": "else",
    "fidhing": "fishing",
    "goke": "joke",
    "hlpe": "help",
    "kniw": "know",
    "knoe": "know",
    "monitered": "monitored",
    "psycologist": "psychologist",
    "riight": "right",
    "scarin": "scaring",
    "seriosly": "seriously",
    "significane": "significance",
    "skeleten": "skeleton",
    "ahmm": "hmm",
    "bcuz": "because",
    "birhday": "birthday",
    "chocolat": "chocolate",
    "coz": "because",
    "femake": "female",
    "fruends": "friends",
    "ghosy": "ghost",
    "haahaa": "haha",
    "heheh": "hehe",
    "whrn": "when",
    "lige": "life",
    "nothinh": "nothing",
    "prob": "problem",
    "secund": "second",
    "soryy": "sorry",
    "teally": "really",
    "theres": "there is",
    "tiref": "tired",
    "whooaa": "whoa",
    "qho": "who",
    "qhy": "why",
    "sware": "swear",
    "ues": "yes",
    "promice": "promise",
    "rhere": "there",
    "rhis": "this",
    "sipder": "spider",
    "thqt": "that",
    "annying": "annoying",
    "borinh": "boring",
    "crreppy": "creepy",
    "gane": "game",
    "herw": "here",
    "hhmm": "hmm",
    "saided": "said",
    "pics": "pictures",
    "plaboy": "playboy",
    "plis": "please",
    "soonglasses": "sunglasses",
    "thankd": "thanks",
    "thankuu": "thank you",
    "thankx": "thanks",
    "tjanks": "thanks",
    "wyh": "why",
    "youer": "your",
    "leve": "leave",
    "nigth": "night",
    "storry": "story",
    "teaxh": "teach",
    "tel": "tell",
    "looj": "look",
    "medicion": "medicine",
    "datw": "date",
    "pleaes": "please",
    "gudbye": "good bye",
    "welocome": "welcome",
    "ghast": "ghost",
    "gimmie": "give me",
    "sometin": "something",
    "yoi": "you",
    "bpyfriend": "boyfriend",
    "dsre": "dare",
    "lieng": "lying",
    "lyk": "like",
    "weres": "where is",
    "argh": "aargh",
    "bothet": "bother",
    "famileir": "familiar",
    "finallyy": "finally",
    "ghosstt": "ghost",
    "hobis": "hobbies",
    "lonlines": "loneliness",
    "nit": "not",
    "tierd": "tired",
    "alobe": "alone",
    "dis": "this",
    "gitl": "girl",
    "homless": "homeless",
    "merri": "marry",
    "merrie": "marry",
    "noww": "now",
    "pap": "dad",
    "skelliton": "skeleton",
    "thanku": "thank you",
    "blivein": "believe in",
    "cementary": "cemetery",
    "cindi": "cindy",
    "damm": "damn",
    "hustbun": "husband",
    "ikonw": "i know",
    "lovly": "lovely",
    "semetery": "cemetery",
    "shiw": "show",
    "girlfriwnd": "girlfriend",
    "hlo": "hello",
    "noy": "not",
    "serpantza": "serpentza",
    "wjo": "who",
    "d0g": "dog",
    "everythinf": "everything",
    "everythint": "everything",
    "facd": "face",
    "followe": "follow",
    "ghostt": "ghost",
    "hidee": "hide",
    "jihn": "john",
    "ma'am": "madam",
    "minite": "minute",
    "neithet": "neither",
    "notjin": "nothing",
    "qhat": "what",
    "skeletom": "skeleton",
    "skelton": "skeleton",
    "sorr": "sorry",
    "suprise": "surprise",
    "talj": "talk",
    "thsn": "than",
    "ughly": "ugly",
    "whoaa": "whoa",
    "yestrday": "yesterday",
    "sensr": "sense",
    "wud": "what you doing",
    "airzona": "arizona",
    "aorry": "sorry",
    "awsomr": "awesome",
    "becease": "because",
    "datung": "dating",
    "dleep": "sleep",
    "dp": "do",
    "frienda": "friends",
    "ghoasttown": "ghosttown",
    "goodbyr": "goodbye",
    "hhahaa": "haha",
    "ia": "is",
    "jerrk": "jerk",
    "jonh": "john",
    "lile": "like",
    "mqn": "man",
    "princesa": "princess",
    "ralk": "talk",
    "sekf": "self",
    "semintary": "cemetery",
    "serease": "serious",
    "tou": "you",
    "weard": "weird",
    "adoable": "adorable",
    "crine": "crime",
    "leta": "let's",
    "suree": "sure",
    "milaydy": "milady",
    "nise": "nice",
    "reely": "really",
    "restaurantes": "restaurants",
    "yrs": "yes",
    "y'know": "you know",
    "basment": "basement",
    "bcoz": "because",
    "boyfrade": "boyfriend",
    "boyfrian": "boyfriend",
    "boyfruend": "boyfriend",
    "girlfruend": "girlfriend",
    "hamburguees": "hamburgers",
    "hwllo": "hello",
    "np": "no problem",
    "sexi": "sexy",
    "yeay": "yay",
    "dident": "didn't",
    "housw": "house",
    "owkey": "ok",
    "arigato": "arigatou",
    "spageti": "spaghetti",
    "sweatt": "sweat",
    "boreing": "boring",
    "borinf": "boring",
    "grilfriende": "girlfriend",
    "honna": "going to",
    "peoms": "poems",
    "spaghetty": "spaghetti",
    "yees": "yes",
    "yesterdat": "yesterday",
    "immitatr": "imitate",
    "coffe": "coffee",
    "cyao": "ciao",
    "qith": "with",
    "vegetariano": "vegetarian",
    "abot": "about",
    "akready": "already",
    "beauriful": "beautiful",
    "blushs": "blushes",
    "comeon": "come on",
    "cutw": "cute",
    "fucj": "fuck",
    "happu": "happy",
    "honeyy": "honey",
    "kets": "let's",
    "oke": "ok",
    "realzz": "really",
    "senpia": "senpai",
    "sexx": "sex",
    "thwn": "then",
    "tokd": "told",
    "understen": "understand",
    "favourate": "favorite",
    "hooman": "human",
    "abat": "about",
    "anythink": "anything",
    "baibe": "babe",
    "beacg": "beach",
    "beautifu": "beautiful",
    "beuatiful": "beautiful",
    "boifrend": "boyfriend",
    "clothe": "clothes",
    "clothses": "clothes",
    "colore": "color",
    "covk": "chick",
    "dsddy": "daddy",
    "ehat": "what",
    "ehats": "what is",
    "faborite": "favorite",
    "forevee": "forever",
    "fuun": "fun",
    "goinf": "going",
    "h-hi": "hi",
    "ı": "i",
    "itslef": "itself",
    "jaket": "jacket",
    "lalalalala": "la la la",
    "lamborghini's": "",
    "lonelu": "lonely",
    "m'y": "my",
    "magdonald": "mcdonald's",
    "niw": "now",
    "obe": "one",
    "oki": "ok",
    "oreng": "orange",
    "pregnante": "pregnant",
    "righr": "right",
    "rigth": "right",
    "sabastion": "sebastian",
    "se3": "see",
    "sebstain": "sebastian",
    "sempai": "senpai",
    "somrthing": "something",
    "sorri": "sorry",
    "spaguetti": "spaghetti",
    "stramge": "strange",
    "stup'd": "stupid",
    "tellme": "tell me",
    "ugli": "ugly",
    "ugoy": "ugly",
    "borung": "boring",
    "cutee": "cute",
    "enything": "anything",
    "favorate": "favorite",
    "fovoreat": "favorite",
    "girfrend": "girlfriend",
    "hoby": "hobby",
    "morr": "more",
    "sebatian": "sebastian",
    "sweetjeart": "sweetheart",
    "tommorw": "tomorrow",
    "vanpires": "vampires",
    "vert": "very",
    "blusing": "blushing",
    "donw": "done",
    "faliing": "falling",
    "pwease": "please",
    "sabachion": "sebastian",
    "seabetian": "sebastian",
    "seasbation": "sebastian",
    "somting": "something",
    "sumb": "dumb",
    "clothis": "clothes",
    "mony": "money",
    "t-thanks": "thanks",
    "cheken": "chicken",
    "ilove": "i love",
    "seb": "sebastian",
    "volibaal": "volleyball",
    "witj": "with",
    "witress": "waitress"
};

GHOST.shortcuts = {
    "to late": "too late",
    "j pop": "j-pop",
    "k pop": "k-pop",
    "snow man": "snowman",
    "snow men": "snowmen",
    "name s": "name is",
    "water fall": "waterfall",
    "can , t": "can't",
    "can not": "can't",
    "do not": "don't",
    "could not": "couldn't",
    "will not": "won't",
    "are not": "aren't",
    "is not": "isn't",
    "have not": "haven't",
    "was not": "wasn't",
    "did not": "didn't",
    "does not": "doesn't",
    "were not": "weren't",
    "would not": "wouldn't",
    "should not": "shouldn't",
    "let us": "let's",
    "square route": "square root",
    "you go oh": "yu-gi-oh",
    "a . i .": "ai",
    "a . i": "ai",
    "em i": "am i",
    "girl friend": "girlfriend",
    "boy friend": "boyfriend",
    "some one": "someone",
    "me 2": "me too",
    "nows me": "knows me",
    "to meat you": "to meet you",
    "wi fi": "wifi",
    "i m": "i am",
    "i , m": "i am",
    "i , am": "i am",
    "b day": "birthday",
    "are . i . p": "rip",
    "oh . m . g": "omg",
    "you . s . a .": "usa",
    "you . s . a": "usa",
    "you . s": "usa",
    "d pressed": "depressed",
    "what evr": "whatever",
    "you tuber": "youtuber",
    "see + +": "cplusplus",
    "hes not": "he is not",
    "any body": "anybody",
    "hack saw": "hacksaw",
    "home work": "homework",
    "pop corn": "popcorn",
    "were threw": "we are through",
    "l . oh . v . e": "love"
};
// Node.js support
if (typeof module === 'object' && module.exports) {
    module.exports = { slang: GHOST.slang, shortcuts: GHOST.shortcuts };
}